### PR TITLE
Add binding_of_caller gem to development

### PR DESCRIPTION
**Pull request by pollygee**

### CODE REVIEW

**Comment by jamesdabbs** [comment]
#2

**Comment by jamesdabbs** [comment]
Can we move that to the `development` group underneath `better_errors`?

**Comment by jamesdabbs** [comment]
Also, I hate this.

**Comment by jamesdabbs** [comment]
Just kidding, sorry.

**Comment by pollygee** [comment]
So I made the change you asked for I can't see a place to make another pull request, so do the code changes just get reflected here?

**Comment by jamesdabbs** [comment]
Yep. In fact _it's already in the list of commits for this PR (above)_. 

magic

**Pull request merged**
